services:
  jaeger:
    image: jaegertracing/jaeger:latest
    command: ["--config=/etc/jaeger/config.yaml"]
    volumes:
      - jaeger_badger_data:/badger
      - ./jaeger-config.yaml:/etc/jaeger/config.yaml:ro
    ports:
      - "16686:16686"
    depends_on:
      prepare-data-dir:
        condition: service_completed_successfully

  prepare-data-dir:
    user: root
    image: busybox:latest
    command: "sh -c 'mkdir -p /badger/data && chown -R 10001:10001 /badger/data'"
    volumes:
      - jaeger_badger_data:/badger


  otel-collector:
    image: otel/opentelemetry-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger

  wordfreq-api:
    build: .
    image: enuno/word-freq-api:latest
    volumes:
      - ${DATA_DIR:-./data}:/data:ro
    environment:
      APP_ENV: ${APP_ENV:-dev}
      DUCKDB_PATH: /data/ngrams.duckdb
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_SERVICE_NAME: "wordfreq-api"
    ports:
      - "8000:8000"
    depends_on:
      - otel-collector

volumes:
  jaeger_badger_data: