[project]
name = "word-freq-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckdb>=1.5.2",
    "fastapi[standard-no-fastapi-cloud-cli]>=0.135.1",
    "google-cloud-bigquery>=3.40.1",
    "httpx>=0.28.1",
    "opentelemetry-distro>=0.63b1",
    "opentelemetry-exporter-otlp>=1.42.1",
    "opentelemetry-instrumentation-asyncio==0.63b1",
    "opentelemetry-instrumentation-click==0.63b1",
    "opentelemetry-instrumentation-dbapi==0.63b1",
    "opentelemetry-instrumentation-fastapi==0.63b1",
    "opentelemetry-instrumentation-grpc==0.63b1",
    "opentelemetry-instrumentation-httpx==0.63b1",
    "opentelemetry-instrumentation-jinja2==0.63b1",
    "opentelemetry-instrumentation-logging==0.63b1",
    "opentelemetry-instrumentation-requests==0.63b1",
    "opentelemetry-instrumentation-sqlite3==0.63b1",
    "opentelemetry-instrumentation-starlette==0.63b1",
    "opentelemetry-instrumentation-threading==0.63b1",
    "opentelemetry-instrumentation-tortoiseorm==0.63b1",
    "opentelemetry-instrumentation-urllib==0.63b1",
    "opentelemetry-instrumentation-urllib3==0.63b1",
    "opentelemetry-instrumentation-wsgi==0.63b1",
    "opentelemetry-sdk>=1.40.0",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
    "pypika>=0.51.1",
    "sqlglot>=30.4.3",
]

[tool.fastapi]
entrypoint = "src.main:app"

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pyright>=1.1.408",
    "pytest>=9.0.2",
    "ruff>=0.15.11",
]

[tool.pyright]
# ...
venvPath = "."
venv = ".venv"

[tool.ruff.lint]
ignore = ["E402"]
