name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.7"
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.14

      - name: Install dependencies
        run: uv sync --frozen

      - name: Type check
        run: uv run pyright .

        # In case pre-commit hook is forgotten
      - name: Format check
        run: uv run ruff format --check .

      - name: Lint Check
        run: uv run ruff check .

      - name: Run tests
        run: uv run pytest

  build_image:
    name: docker
    needs: test
    runs-on: ubuntu-latest

    steps:
    
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        if: github.event_name == 'push'
        uses: docker/build-push-action@v7
        with:
            push: true
            tags: ${{ vars.DOCKERHUB_USERNAME }}/word-freq-api:latest



